[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.14"
serde = { version = "1.0", features = ["derive"] }
regex = "1.10.5"
clap = { version = "4.5.9", features = ["derive"] }
chrono = "0.4.38"
