##############
### ROUTES ###
##############

# Main Route
[http.routes."main"]
ports = [ "2" ]
hosts = [ "example.com", "127.0.0.1", "localhost" ]
# priority = 3
# force_host = false
# force_ssl = false

[http.routes."main".paths."^/"]
service = "html"
[http.routes."main".paths."^/static"]
service = "static"
[http.routes."main".paths."^/(admin|link)"]
service = "django"

# Link Shortener route
[http.routes."go"]
ports = [ "2" ]
hosts = [ "example.com" ]
# priority = 10
# force_ssl = false
# force_host = false

[http.routes."go".paths."^/"]
service = "go"

# Forbidden Route
[http.routes."403"]
ports = [ "2" ]
hosts = [ "forbidden.example.com" ]
# priority = 2
# force_ssl = false
# force_host = false

[http.routes."403".paths."^/"]
service = "403"

################
### SERVICES ###
################

[http.services."html"]
module = "web-server"
action = """
    index = "index.html"
"""

[http.services."static"]
module = "web-server"
action = """
    root = "/srv/www/static/"
"""

[http.services."django"]
module = "reverse-proxy"
action = """
    target = "http://localhost:8080/"
"""

[http.services."go"]
module = "web-server"
action = """
    return = "301 https://example.com/link/open/"
"""

[http.services."403"]
module = "web-server"
action = """
    return = "403"
"""