modules:
  web-server: ../modules/web-server/target/release/libweb_server.so
  # reverse-proxy: ../modules/reverse-proxy/target/release/libreverse_proxy.so
http:
  routes:
    rickroll:
      ports:
        - "65080"
      hosts:
        - ayilmaz.xyz
        - localhost
        - "127.0.0.1"
      paths:
        ^/:
          service: rickroll
  services:
    rickroll:
      module: web-server
      parameters:
        return: 301
        location: https://www.youtube.com/watch?v=dQw4w9WgXcQ
