##############
### ROUTES ###
##############
[http.routes]

# Main Route
[http.routes."main"]
ports = [ "65080" ]
hosts = [ "127.0.0.1", "localhost" ]

[http.routes."main".paths."^/"]
service = "index"

################
### SERVICES ###
################
[http.services]

[http.services."index"]
module = "web-server"
[http.services."index".parameters]
index = "/srv/www/index.html"