modules:
  web-server: ../modules/web-server/target/release/libweb_server.so
  reverse-proxy: ../modules/reverse-proxy/target/release/libreverse_proxy.so
http:
  max_body_size: 50000000 # doesn't support letters yet. enter as bytes

  routes:
    server:
      priority: 5
      ports:
        - "65080"
      hosts:
        - localhost
        - 127.0.0.1
      paths:
        ^/: reverse

  services:
    reverse:
      module: reverse-proxy
      parameters:
        upstreams:
          - "1"
          - "2"
          - "3"
          - "4"
    index:
      module: web-server
      parameters:
        file: index.html
        root: /home/yilmaz/Other/GitHub/rusty/html/
