modules:
  web-server: ../modules/web-server/target/release/libweb_server.so
  # reverse-proxy: ../modules/reverse-proxy/target/release/libreverse_proxy.so
http:
  max_body_size: 50000000 # doesn't support letters yet. enter as bytes

  routes:
    mirror:
      priority: 5
      ports:
        - "65080"
      hosts:
        - localhost
        - 127.0.0.1
      paths:
        ^/: index
        ^/.+: fileserver

  services:
    index:
      module: web-server
      parameters:
        location: https://ayilmaz.xyz
    fileserver:
      module: web-server
      parameters:
        root: "/srv/mirror/"
        file: $request_uri_trimmed$
