modules:
  web-server: ../modules/web-server/target/release/libweb_server.so
  # reverse-proxy: ../modules/reverse-proxy/target/release/libreverse_proxy.so
http:
  routes:
    main:
      ports:
        - "65080"
      hosts:
        - 127.0.0.1
        - localhost
      paths:
        ^/:
          service: index
        ^/.+:
          service: files

  services:
    index:
      module: web-server
      parameters:
        file: index.html
        root: /home/yilmaz/Other/GitHub/rusty/html/
    files:
      module: web-server
      parameters:
        file: $request_uri$
        root: /home/yilmaz/Other/GitHub/rusty/html/
